begin;
do $$
declare org uuid:=gen_random_uuid(); other_org uuid:=gen_random_uuid(); admin_id uuid:=gen_random_uuid(); author uuid:=gen_random_uuid(); approver uuid:=gen_random_uuid(); twin uuid:=gen_random_uuid(); outsider uuid:=gen_random_uuid(); rid text:=gen_random_uuid()::text; foreign_rid text:=gen_random_uuid()::text; doc jsonb; payload jsonb; saved jsonb; nextdoc jsonb; result jsonb; bound jsonb; original jsonb;
begin
 insert into core.organizations(id,name,status) values(org,'Authorization test','active'),(other_org,'Other auth','active');
 insert into auth.users(id) values(admin_id),(author),(approver),(twin),(outsider);
 insert into finance.reimbursement_members values(org,admin_id,'Admin',array['ADMIN'],true),(org,author,'Writer',array['PAY'],true),(org,approver,'Same name',array['APPROVE'],true),(org,twin,'Same name','{}',true),(other_org,outsider,'Foreign',array['ADMIN'],true);
 doc:=jsonb_build_object('id',rid,'author','Caller label','approvalStatus','작성중','paymentStatus','지급전','settlementStatus','정산없음','totalPaymentAmount',100,'resolutionType','SINGLE','expenseTiming','ADVANCE','expenseItems','[]'::jsonb,'history','[]'::jsonb,'approvalLine',jsonb_build_array(jsonb_build_object('approver','Same','role','name','status','대기')));
 payload:=jsonb_build_object('row',jsonb_build_object('id',rid,'resolution_no','AUTH-1','author_label','Caller label','approval_status','작성중','payment_status','지급전','total_payment_amount',100,'resolution_data',doc,'actual_paid_amount',null,'voucher_no',null,'voucher_status',null,'disbursed_at',null),'items',jsonb_build_array(jsonb_build_object('id','item-'||rid,'resolution_id',rid,'item_kind','SINGLE','item_no',1,'supply_amount',100,'vat_amount',0,'total_amount',100,'item_data','{}'::jsonb)),'allocations','[]'::jsonb,'evidence','[]'::jsonb,'details','[]'::jsonb);
 begin perform finance.legacy_expense_command(org,author,'SAVE',rid,null,jsonb_set(payload,'{row,disbursed_at}','"2026-03-01"'),'forged-new-paid');raise exception 'TEST: new paid timestamp';exception when others then if sqlerrm not like '%실제 지급 또는 전표%' then raise;end if;end;
 begin perform finance.legacy_expense_command(org,author,'SAVE',rid,null,jsonb_set(payload,'{row,resolution_data,paidAt}','"2026-03-01"'),'forged-new-json-paid');raise exception 'TEST: new JSON paid';exception when others then if sqlerrm not like '%실제 완료 결과%' then raise;end if;end;
 begin perform finance.legacy_expense_command(org,author,'SAVE',rid,null,jsonb_set(payload,'{row,resolution_data,settlementStatus}','"정산완료"'),'forged-new-settlement');raise exception 'TEST: new completed settlement';exception when others then if sqlerrm not like '%정산완료%' then raise;end if;end;
 saved:=finance.legacy_expense_command(org,author,'SAVE',rid,null,payload,'create');
 if saved->>'author'<>'Writer' or (select author_user_id from finance.expense_authorization_bindings where resolution_id=rid)<>author then raise exception 'TEST: authenticated author not bound'; end if;
 if finance.legacy_expense_command(org,author,'SAVE',rid,null,payload,'create')<>saved then raise exception 'TEST: retry changed result'; end if;
 begin perform finance.legacy_expense_command(org,twin,'SAVE',rid,saved,payload,'twin-save'); raise exception 'TEST: same name edited'; exception when others then if sqlerrm not like '%작성자 연결%' then raise; end if; end;
 begin perform finance.legacy_expense_command(other_org,outsider,'DELETE',rid,saved,'{"reason":"foreign"}','foreign-delete'); raise exception 'TEST: foreign edit'; exception when others then if sqlerrm not like '%조직의 지출결의%' then raise; end if; end;
 nextdoc:=saved||jsonb_build_object('approvalStatus','승인대기','currentApprover','Same name','approvalLine',jsonb_build_array(jsonb_build_object('approver','Same','role','name','status','결재대기')),'history',jsonb_build_array(jsonb_build_object('action','request')));
 begin perform finance.legacy_expense_command(org,author,'APPROVAL',rid,saved,jsonb_build_object('command','REQUEST','after',nextdoc),'unbound-request'); raise exception 'TEST: unresolved approver allowed'; exception when others then if sqlerrm not like '%UUID 연결%' then raise; end if; end;
 bound:=finance.legacy_expense_command(org,admin_id,'BIND',rid,saved,jsonb_build_object('author_user_id',author,'steps',jsonb_build_array(jsonb_build_object('order',1,'approver_user_id',approver)),'reason','Verified actual identity','expected_binding_version',1),'bind');
 if (select resolution_data from finance.expense_resolutions where id=rid)<>saved then raise exception 'TEST: binding rewrote original'; end if;
 saved:=finance.legacy_expense_command(org,author,'APPROVAL',rid,saved,jsonb_build_object('command','REQUEST','after',nextdoc),'request');
 original:=saved;
 payload:=jsonb_set(payload,'{row,resolution_data}',(saved-'currentApprover')||jsonb_build_object('approvalStatus','작성중'));
 saved:=finance.legacy_expense_command(org,author,'SAVE',rid,saved,payload,'edit-pending');
 if saved->>'approvalStatus'<>'작성중' or saved->'history' is distinct from original->'history' or saved#>>'{approvalLine,0,status}'<>'결재대기' then raise exception 'TEST: pending edit did not preserve history and reset approval'; end if;
 begin perform finance.legacy_expense_command(org,author,'SAVE',rid,original,payload,'stale-pending-edit');raise exception 'TEST: stale pending edit';exception when others then if sqlerrm not like '%원본이 변경%' then raise;end if;end;
 begin perform finance.legacy_expense_command(org,author,'SAVE',rid,saved,jsonb_set(payload,'{row,resolution_data,paidAt}','"2026-03-01"'),'forged-existing-paid');raise exception 'TEST: existing JSON paid';exception when others then if sqlerrm not like '%실제 지급·정산·전표%' then raise;end if;end;
 nextdoc:=saved||jsonb_build_object('approvalStatus','승인대기','currentApprover','Same name','history',(saved->'history')||jsonb_build_array(jsonb_build_object('action','rerequest')));
 saved:=finance.legacy_expense_command(org,author,'APPROVAL',rid,saved,jsonb_build_object('command','REQUEST','after',nextdoc),'rerequest');
 nextdoc:=(saved-'currentApprover')||jsonb_build_object('approvalStatus','승인완료','paymentStatus','지급대기','approvedAt','2026-09-08T10:00:00+09:00','approvalLine',jsonb_build_array(jsonb_build_object('approver','Same','role','name','status','승인완료','processedAt','2026-09-08T10:00:00+09:00')),'history',(saved->'history')||jsonb_build_array(jsonb_build_object('action','approve')));
 begin perform finance.legacy_expense_command(org,twin,'APPROVAL',rid,saved,jsonb_build_object('command','APPROVE','after',nextdoc),'twin-approval'); raise exception 'TEST: same label approved'; exception when others then if sqlerrm not like '%현재 연결된 결재자%' then raise; end if; end;
 begin perform finance.legacy_expense_command(org,approver,'APPROVAL',rid,saved,jsonb_build_object('command','APPROVE','after',nextdoc||'{"totalPaymentAmount":999}'),'forged-amount'); raise exception 'TEST: forged amount'; exception when others then if sqlerrm not like '%금액 또는 원본%' then raise; end if; end;
 original:=saved;
 saved:=finance.legacy_expense_command(org,approver,'APPROVAL',rid,saved,jsonb_build_object('command','APPROVE','after',nextdoc),'approve');
 if saved->>'approvalStatus'<>'승인완료' or (select total_payment_amount from finance.expense_resolutions where id=rid)<>100 then raise exception 'TEST: approval changed amount'; end if;
 begin perform finance.legacy_expense_command(org,approver,'APPROVAL',rid,original,jsonb_build_object('command','APPROVE','after',nextdoc),'stale-approval'); raise exception 'TEST: stale approval'; exception when others then if sqlerrm not like '%원본이 변경%' then raise; end if; end;
 if not exists(select 1 from finance.expense_workflow_audit_logs where resolution_id=rid and actor_id=approver and action='AUTH:APPROVAL') then raise exception 'TEST: missing UUID audit'; end if;
 if (select approved_at from finance.expense_resolutions where id=rid) is distinct from '2026-09-08T01:00:00Z'::timestamptz then raise exception 'TEST: approval timezone changed'; end if;
 -- New draft: bad child must roll back header and author binding.
 rid:=gen_random_uuid()::text; payload:=jsonb_set(payload,'{row,id}',to_jsonb(rid)); payload:=jsonb_set(payload,'{row,resolution_no}','"AUTH-BAD"'); payload:=jsonb_set(payload,'{row,resolution_data,id}',to_jsonb(rid));
 payload:=jsonb_set(payload,'{items,0,resolution_id}',to_jsonb(rid));
 begin perform finance.legacy_expense_command(org,author,'SAVE',rid,null,payload,'stolen-child'); raise exception 'TEST: child stolen'; exception when others then if sqlerrm not like '%다른 원본의 상세%' then raise; end if; end;
 if exists(select 1 from finance.expense_resolutions where id=rid) then raise exception 'TEST: failed child persisted header'; end if;
 payload:=jsonb_set(payload,'{items,0,id}',to_jsonb('new-'||rid));payload:=jsonb_set(payload,'{items,0,total_amount}','99');
 begin perform finance.legacy_expense_command(org,author,'SAVE',rid,null,payload,'bad-total'); raise exception 'TEST: child total'; exception when others then if sqlerrm not like '%항목 합계%' then raise; end if; end;
 payload:=jsonb_set(payload,'{items,0,total_amount}','100');
 begin perform finance.legacy_expense_command(org,author,'SAVE',rid,null,payload||jsonb_build_object('details',jsonb_build_array(jsonb_build_object('id','bad-detail-'||rid,'resolution_id',rid,'line_no',1))),'child-insert-failure'); raise exception 'TEST: invalid child written'; exception when not_null_violation then null; end;
 if exists(select 1 from finance.expense_resolutions where id=rid) or exists(select 1 from finance.expense_authorization_bindings where resolution_id=rid) or exists(select 1 from finance.expense_workflow_audit_logs where resolution_id=rid) then raise exception 'TEST: partial header/binding/audit persisted'; end if;
 saved:=finance.legacy_expense_command(org,author,'SAVE',rid,null,payload,'good-draft');
 result:=finance.legacy_expense_command(org,author,'DELETE',rid,saved,'{"reason":"Draft withdrawn"}','delete');
 if not exists(select 1 from finance.expense_resolutions where id=rid and deleted_at is not null) or not exists(select 1 from finance.expense_resolution_items where resolution_id=rid) then raise exception 'TEST: soft delete removed original children'; end if;
 if (select count(*) from finance.expense_authorization_operations where organization_id=org and operation_key='delete')<>1 then raise exception 'TEST: delete operation count'; end if;
end $$;
do $$
declare org uuid:=gen_random_uuid(); actor uuid:=gen_random_uuid(); bank uuid:=gen_random_uuid(); acct uuid:=gen_random_uuid(); card uuid:=gen_random_uuid(); rid text:=gen_random_uuid()::text; doc jsonb; payload jsonb; saved jsonb;
begin
 insert into core.organizations(id,name,status) values(org,'Atomic links','active');insert into auth.users(id) values(actor);
 insert into finance.reimbursement_members values(org,actor,'Admin',array['ADMIN'],true);
 insert into finance.bank_accounts(id,organization_id,bank_name,account_name,account_no,account_type) values(acct,org,'Bank','Operating',acct::text,'운영계좌');
 insert into finance.bank_transactions(id,organization_id,bank_account_id,transacted_at,description,withdrawal_amount,deposit_amount) values(bank,org,acct,'2026-03-01','Payment',100,0);
 insert into finance.corporate_card_transactions(id,organization_id,transaction_uid,approved_at,amount,card_name,card_last_four) values(card,org,card::text,'2026-03-01',100,'Test','1234');
 doc:=jsonb_build_object('id',rid,'author','Forged','approvalStatus','작성중','paymentStatus','지급전','totalPaymentAmount',100,'bankTransactionId',bank,'cardTransactionId',card,'history',jsonb_build_array(jsonb_build_object('actorName','Forged')),'evidenceStatus','NONE');
 payload:=jsonb_build_object('row',jsonb_build_object('id',rid,'resolution_no','LINKS','author_label','Forged','approval_status','작성중','payment_status','지급전','total_payment_amount',100,'bank_transaction_id',bank,'resolution_data',doc,'actual_paid_amount',null,'voucher_no',null,'voucher_status',null,'disbursed_at',null),'items','[]'::jsonb,'allocations','[]'::jsonb,'evidence','[]'::jsonb,'details','[]'::jsonb);
 saved:=finance.legacy_expense_command(org,actor,'SAVE',rid,null,payload,'links-create');
 if saved->>'author'<>'Admin' or saved->'history'<>'[]'::jsonb then raise exception 'TEST: forged author/history'; end if;
 if (select resolution_status from finance.bank_transactions where id=bank)<>'EVIDENCE_MISSING' or not exists(select 1 from finance.corporate_card_transactions where id=card and linked_resolution_id=rid and resolution_status='EVIDENCE_MISSING') then raise exception 'TEST: atomic links absent'; end if;
 begin update finance.expense_resolutions set approval_status='승인완료' where id=rid;raise exception 'TEST: direct approval bypass';exception when others then if sqlerrm not like '%원자적 저장%' then raise;end if;end;
 begin insert into finance.expense_resolution_items(id,resolution_id,item_kind,item_no,item_data) values('bypass-'||rid,rid,'SINGLE',1,'{}');raise exception 'TEST: direct child bypass';exception when others then if sqlerrm not like '%원자적 저장%' then raise;end if;end;
 perform finance.legacy_expense_command(org,actor,'DELETE',rid,saved,'{"reason":"Withdraw"}','links-delete');
 if (select resolution_status from finance.bank_transactions where id=bank)<>'UNRESOLVED' or not exists(select 1 from finance.corporate_card_transactions where id=card and linked_resolution_id is null and resolution_status='UNRESOLVED') then raise exception 'TEST: deleted links retained'; end if;
end $$;
do $$
declare org uuid:=gen_random_uuid(); actor uuid:=gen_random_uuid(); rid text:=gen_random_uuid()::text; detail text:='detail-'||rid; doc jsonb; payload jsonb; saved jsonb; input jsonb; result jsonb; first_id uuid; second_id uuid;
begin
 insert into core.organizations(id,name,status) values(org,'Fact atomic','active');insert into auth.users(id) values(actor);insert into finance.reimbursement_members values(org,actor,'Verified writer',array['PAY'],true);
 doc:=jsonb_build_object('id',rid,'author','Writer','approvalStatus','작성중','paymentStatus','지급전','totalPaymentAmount',100,'history','[]'::jsonb);
 payload:=jsonb_build_object('row',jsonb_build_object('id',rid,'resolution_no','FACT','author_label','Writer','approval_status','작성중','payment_status','지급전','total_payment_amount',100,'resolution_data',doc,'actual_paid_amount',null,'voucher_no',null,'voucher_status',null,'disbursed_at',null),'items','[]'::jsonb,'allocations','[]'::jsonb,'evidence','[]'::jsonb,'details',jsonb_build_array(jsonb_build_object('id',detail,'resolution_id',rid,'line_no',1,'transaction_date','2026-03-01','actual_spender_label','Writer','vendor_name','Shop','item_name','Supplies','business_purpose','Office','account_title','Office','amount',100,'payment_method','CASH')));
 saved:=finance.legacy_expense_command(org,actor,'SAVE',rid,null,payload,'fact-original');
 input:=jsonb_build_object('resolutionId',rid,'detailTransactionId',detail,'actualSpender','Writer','actualExpenseDate','2026-03-01','vendorName','Shop','itemDescription','Supplies','amount',100,'businessPurpose','Office','missingReceiptReason','Lost receipt','paymentMethod','CASH','authorLabel','Forged');
 result:=finance.legacy_expense_command(org,actor,'FACT_SAVE',rid,saved,jsonb_build_object('input',input,'expected_binding_version',1),'fact-create');first_id:=(result->>'id')::uuid;
 if not exists(select 1 from finance.expense_detail_transactions where id=detail and fact_confirmation_id=first_id and evidence_status='ALTERNATIVE') or not exists(select 1 from finance.expense_fact_confirmations where id=first_id and author_label='Verified writer' and revision_no=1) then raise exception 'TEST: fact link/verified author absent';end if;
 if finance.legacy_expense_command(org,actor,'FACT_SAVE',rid,saved,jsonb_build_object('input',input,'expected_binding_version',1),'fact-create')<>result then raise exception 'TEST: fact retry duplicate';end if;
 input:=input||jsonb_build_object('id',first_id);
 begin perform finance.legacy_expense_command(org,actor,'FACT_SAVE',rid,saved,jsonb_build_object('input',input||'{"actualExpenseDate":"not-a-date"}','expected_binding_version',2),'fact-failed-revision');raise exception 'TEST: malformed revision saved';exception when invalid_datetime_format then null;end;
 if not exists(select 1 from finance.expense_fact_confirmations where id=first_id and is_current) or (select count(*) from finance.expense_fact_confirmations where resolution_id=rid)<>1 then raise exception 'TEST: failed revision retired old fact';end if;
 begin perform finance.legacy_expense_command(org,actor,'FACT_SAVE',rid,saved,jsonb_build_object('input',input||'{"electronicConfirmation":{}}','expected_binding_version',2),'fact-signature');raise exception 'TEST: signature allowed';exception when others then if sqlerrm not like '%서명은 권한 정책%' then raise;end if;end;
 result:=finance.legacy_expense_command(org,actor,'FACT_SAVE',rid,saved,jsonb_build_object('input',input,'expected_binding_version',2),'fact-revise');second_id:=(result->>'id')::uuid;
 if not exists(select 1 from finance.expense_fact_confirmations where id=first_id and not is_current and deleted_at is null) or not exists(select 1 from finance.expense_fact_confirmations where id=second_id and is_current and revision_no=2) then raise exception 'TEST: revision history lost';end if;
 perform finance.legacy_expense_command(org,actor,'FACT_DELETE',rid,saved,jsonb_build_object('input',jsonb_build_object('id',second_id,'resolutionId',rid),'expected_binding_version',3),'fact-delete');
 if not exists(select 1 from finance.expense_detail_transactions where id=detail and fact_confirmation_id is null and evidence_status='DEFICIENT') or not exists(select 1 from finance.expense_fact_confirmations where id=second_id and deleted_at is not null) then raise exception 'TEST: fact delete unlink incomplete';end if;
 if (select resolution_data from finance.expense_resolutions where id=rid)<>saved then raise exception 'TEST: fact mutated financial original';end if;
end $$;
set local role authenticated;
do $$ begin
 begin perform finance.legacy_expense_command(gen_random_uuid(),gen_random_uuid(),'SAVE','x',null,'{}','x');raise exception 'TEST: public RPC';exception when insufficient_privilege then null;end;
 begin perform 1 from finance.expense_authorization_bindings;raise exception 'TEST: public bindings';exception when insufficient_privilege then null;end;
end $$;
rollback;
