import { getSupabaseServerClient } from "@/lib/supabase/server";
import { getApprovalSettings } from "./approval-settings-repository";
import { createDefaultApprovalLines, type ExpenseResolution } from "@/features/finance/finance-model";
import { toManagedExpenseResolution } from "@/features/finance/expense-resolution-page";
export type SmallExpense={id:string;expenseDate:string;partnerName:string;description:string;projectName:string;accountSubjectName:string;amount:number;payerLabel:string;memo:string;batchResolutionId?:string};
function client(){const value=getSupabaseServerClient();if(!value)throw new Error("Supabase 서버 연결이 설정되지 않았어.");return value;}
export async function listSmallExpenses():Promise<SmallExpense[]>{const {data,error}=await client().schema("approval").from("small_expenses").select("*").is("deleted_at",null).order("expense_date",{ascending:false});if(error)throw new Error(`소액경비를 불러오지 못했어: ${error.message}`);return (data??[]).map(row=>({accountSubjectName:row.account_subject_name,amount:Number(row.amount),batchResolutionId:row.batch_resolution_id??undefined,description:row.description,expenseDate:row.expense_date,id:row.id,memo:row.memo,partnerName:row.partner_name,payerLabel:row.payer_label,projectName:row.project_name}));}
export async function createSmallExpense(input:Omit<SmallExpense,"id"|"batchResolutionId"> & {evidence?:File}){const settings=await getApprovalSettings();if(input.amount>settings.smallExpenseLimit)throw new Error(`소액결의 한도 ${settings.smallExpenseLimit.toLocaleString("ko-KR")}원을 초과했어.`);const forbidden=/계약|조합원\s*환불|차입|상환|소송|예산\s*외|추가\s*부담/.test(`${input.description} ${input.memo}`);if(forbidden)throw new Error("계약·환불·차입·소송·예산 외·추가부담 업무는 소액결의를 사용할 수 없어.");let evidencePath:string|null=null;if(input.evidence&&input.evidence.size){if(input.evidence.size>10*1024*1024)throw new Error("증빙파일은 10MB 이하여야 해.");evidencePath=`small-expense/${crypto.randomUUID()}-${input.evidence.name.replace(/[^\w.가-힣-]/g,"_")}`;const {error}=await client().storage.from("approval-attachments").upload(evidencePath,await input.evidence.arrayBuffer(),{contentType:input.evidence.type,upsert:false});if(error)throw new Error(`증빙 업로드 실패: ${error.message}`);}const {error}=await client().schema("approval").from("small_expenses").insert({account_subject_name:input.accountSubjectName,amount:input.amount,created_by_label:input.payerLabel,description:input.description,evidence_bucket:evidencePath?"approval-attachments":null,evidence_path:evidencePath,expense_date:input.expenseDate,memo:input.memo,organization_id:settings.organizationId??null,partner_name:input.partnerName,payer_label:input.payerLabel,project_name:input.projectName});if(error)throw new Error(`소액경비 저장 실패: ${error.message}`);}
export async function createSmallExpenseBatch(ids:string[],actorLabel:string){if(!ids.length)throw new Error("일괄 처리할 내역을 선택해줘.");const rows=(await listSmallExpenses()).filter(row=>ids.includes(row.id)&&!row.batchResolutionId);if(rows.length!==ids.length)throw new Error("이미 처리됐거나 찾을 수 없는 내역이 포함됐어.");const total=rows.reduce((sum,row)=>sum+row.amount,0);const today=new Date().toLocaleDateString("en-CA",{timeZone:"Asia/Seoul"});const base:ExpenseResolution={accountHolder:actorLabel,accountNumber:"",approvalLines:createDefaultApprovalLines(),approvalStatus:"DRAFT",bankName:"미지정",budgetItem:"소액경비",createdAt:today,createdBy:actorLabel,createdByTitle:"회계담당",evidenceFiles:[],expenseType:"소액경비",history:[],id:"small-expense-pending",paymentStatus:"BEFORE_PAYMENT",plannedPaymentDate:today,reason:"월별 소액경비 일괄결의",resolutionNo:"생성중",settlementStatus:"SETTLEMENT_PENDING",subject:`${rows[0].expenseDate.slice(0,7)} 소액경비 일괄결의`,supplyAmount:total,totalAmount:total,vatAmount:0,vendorName:"다수 거래처"};const {data,error}=await client().schema("approval").rpc("create_small_expense_batch",{p_actor_label:actorLabel,p_ids:ids,p_resolution_data:toManagedExpenseResolution(base)});if(error)throw new Error(`월별 일괄결의를 만들지 못했어: ${error.message}`);return data as string;}
